DROP DATABASE IF EXISTS xx97_php_react_db;
CREATE DATABASE IF NOT EXISTS xx97_php_react_db
CHARACTER SET utf8mb4
COLLATE utf8mb4_general_ci;

USE xx97_php_react_db;

CREATE TABLE IF NOT EXISTS User (
    id INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS Blog (
    id INT PRIMARY KEY AUTO_INCREMENT,
    title VARCHAR(255) NOT NULL,
    content LONGTEXT NOT NULL
);